import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Header from '@/components/Header'
import Providers from '@/components/Providers'
import { Toaster } from 'sonner'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'antialiased')}>
        <Providers>
          <Header> 
            <NavBar/>
          </Header>
          <main>
            {children}
          </main>
        </Providers>
        <Toaster position='top-center' richColors={true} />
      </body>
    </html>
  )
}
